/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.phieumuon;

import QLTVController.PhieuMuonController;
import Util.CustomTablePhieuTra;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author WIN1064
 */
public class QuanLyPhieuTra extends javax.swing.JPanel {

    PhieuMuonController pmc = new PhieuMuonController();
    int selectedRow;
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    ArrayList<String> loc = new ArrayList<String>();
    String keywords = "";
    String tongPhieuTra;
    /**
     * Creates new form QuanLyPhieuTra
     */
    public QuanLyPhieuTra() {
        initComponents();
        LuuDuLieu.dsPTCT = pmc.getPMCTDaTra();
        loadTable();
        loc.add("Ngày mượn");
        loc.add("Ngày trả");
        jComboBoxLoc.setModel(new DefaultComboBoxModel(loc.toArray()));
        jDateChooserTu.setDateFormatString("dd-MM-yyyy");
        jDateChooserDen.setDateFormatString("dd-MM-yyyy");
        jTablePhieuTra.getTableHeader().setDefaultRenderer(new StyleHeaderTable());
        CustomTablePhieuTra ct = new CustomTablePhieuTra();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTablePhieuTra.getColumnModel().getColumn(2).setPreferredWidth(200);
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTablePhieuTra.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTablePhieuTra.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void loadTable() {
        jTablePhieuTra.setModel(new CustomTablePhieuTra());
        CustomTablePhieuTra ct = new CustomTablePhieuTra();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTablePhieuTra.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTablePhieuTra.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTablePhieuTra.getColumnModel().getColumn(2).setPreferredWidth(200);
        thongKe();
    }
    public void thongKe(){
        tongPhieuTra = Integer.toString(LuuDuLieu.dsPTCT.size());
        jLabelTongPhieuTra.setText("Tổng số phiếu : " + tongPhieuTra);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTaiLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonLoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonTimKiem = new javax.swing.JButton();
        jDateChooserDen = new com.toedter.calendar.JDateChooser();
        jTextKeyWord = new javax.swing.JTextField();
        jComboBoxLoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePhieuTra = new javax.swing.JTable();
        jLabelTongPhieuTra = new javax.swing.JLabel();
        jDateChooserTu = new com.toedter.calendar.JDateChooser();

        jButtonTaiLai.setBackground(new java.awt.Color(0, 204, 255));
        jButtonTaiLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset-20.png"))); // NOI18N
        jButtonTaiLai.setText("Tải lại bảng");
        jButtonTaiLai.setBorder(null);
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Đến ngày");

        jButtonLoc.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLoc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter-20.png"))); // NOI18N
        jButtonLoc.setText("Lọc");
        jButtonLoc.setBorder(null);
        jButtonLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ ngày");

        jButtonTimKiem.setBackground(new java.awt.Color(0, 204, 204));
        jButtonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.setBorder(null);
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jComboBoxLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTablePhieuTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePhieuTra.setFocusable(false);
        jTablePhieuTra.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTablePhieuTra.setRowHeight(25);
        jTablePhieuTra.setSelectionBackground(new java.awt.Color(255, 0, 102));
        jTablePhieuTra.setShowVerticalLines(false);
        jTablePhieuTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePhieuTraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePhieuTra);

        jLabelTongPhieuTra.setText("Tổng số phiếu :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTongPhieuTra)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooserTu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooserDen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jButtonLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(jTextKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jDateChooserTu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxLoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongPhieuTra)
                .addGap(25, 25, 25)
                .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        keywords = jTextKeyWord.getText() + "";
        if (jDateChooserTu.getDate() != null && jDateChooserDen.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tuNgay = sdf.format(jDateChooserTu.getDate());
            String denNgay = sdf.format(jDateChooserDen.getDate());
            LuuDuLieu.dsPTCT = pmc.locPhieuTra(tuNgay, denNgay, keywords, jComboBoxLoc.getSelectedItem().toString());
        } else {
            LuuDuLieu.dsPTCT = pmc.locPhieuTra(null, null, keywords, jComboBoxLoc.getSelectedItem().toString());
        }
        loadTable();
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tuNgay = sdf.format(jDateChooserTu.getDate());
        String denNgay = sdf.format(jDateChooserDen.getDate());
        LuuDuLieu.dsPTCT = pmc.locPhieuTra(tuNgay, denNgay, keywords,jComboBoxLoc.getSelectedItem().toString());
        loadTable();
    }//GEN-LAST:event_jButtonLocActionPerformed

    private void jTablePhieuTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePhieuTraMouseClicked
//        selectedRow = jTableMuonSach.getSelectedRow();
//        LuuDuLieu.currentPhieuMuonChiTiet = Lu/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.phieumuon;

import QLTVController.PhieuMuonController;
import Util.CustomTablePhieuTra;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author WIN1064
 */
public class QuanLyPhieuTra extends javax.swing.JPanel {

    PhieuMuonController pmc = new PhieuMuonController();
    int selectedRow;
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    ArrayList<String> loc = new ArrayList<String>();
    String keywords = "";
    String tongPhieuTra;
    /**
     * Creates new form QuanLyPhieuTra
     */
    public QuanLyPhieuTra() {
        initComponents();
        LuuDuLieu.dsPTCT = pmc.getPMCTDaTra();
        loadTable();
        loc.add("Ngày mượn");
        loc.add("Ngày trả");
        jComboBoxLoc.setModel(new DefaultComboBoxModel(loc.toArray()));
        jDateChooserTu.setDateFormatString("dd-MM-yyyy");
        jDateChooserDen.setDateFormatString("dd-MM-yyyy");
        jTablePhieuTra.getTableHeader().setDefaultRenderer(new StyleHeaderTable());
        CustomTablePhieuTra ct = new CustomTablePhieuTra();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTablePhieuTra.getColumnModel().getColumn(2).setPreferredWidth(200);
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTablePhieuTra.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTablePhieuTra.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void loadTable() {
        jTablePhieuTra.setModel(new CustomTablePhieuTra());
        CustomTablePhieuTra ct = new CustomTablePhieuTra();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTablePhieuTra.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTablePhieuTra.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTablePhieuTra.getColumnModel().getColumn(2).setPreferredWidth(200);
        thongKe();
    }
    public void thongKe(){
        tongPhieuTra = Integer.toString(LuuDuLieu.dsPTCT.size());
        jLabelTongPhieuTra.setText("Tổng số phiếu : " + tongPhieuTra);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTaiLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonLoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonTimKiem = new javax.swing.JButton();
        jDateChooserDen = new com.toedter.calendar.JDateChooser();
        jTextKeyWord = new javax.swing.JTextField();
        jComboBoxLoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePhieuTra = new javax.swing.JTable();
        jLabelTongPhieuTra = new javax.swing.JLabel();
        jDateChooserTu = new com.toedter.calendar.JDateChooser();

        jButtonTaiLai.setBackground(new java.awt.Color(0, 204, 255));
        jButtonTaiLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset-20.png"))); // NOI18N
        jButtonTaiLai.setText("Tải lại bảng");
        jButtonTaiLai.setBorder(null);
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Đến ngày");

        jButtonLoc.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLoc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter-20.png"))); // NOI18N
        jButtonLoc.setText("Lọc");
        jButtonLoc.setBorder(null);
        jButtonLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ ngày");

        jButtonTimKiem.setBackground(new java.awt.Color(0, 204, 204));
        jButtonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.setBorder(null);
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jComboBoxLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTablePhieuTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePhieuTra.setFocusable(false);
        jTablePhieuTra.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTablePhieuTra.setRowHeight(25);
        jTablePhieuTra.setSelectionBackground(new java.awt.Color(255, 0, 102));
        jTablePhieuTra.setShowVerticalLines(false);
        jTablePhieuTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePhieuTraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePhieuTra);

        jLabelTongPhieuTra.setText("Tổng số phiếu :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTongPhieuTra)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooserTu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooserDen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jButtonLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(jTextKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jDateChooserTu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxLoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserDen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongPhieuTra)
                .addGap(25, 25, 25)
                .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        keywords = jTextKeyWord.getText() + "";
        if (jDateChooserTu.getDate() != null && jDateChooserDen.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tuNgay = sdf.format(jDateChooserTu.getDate());
            String denNgay = sdf.format(jDateChooserDen.getDate());
            LuuDuLieu.dsPTCT = pmc.locPhieuTra(tuNgay, denNgay, keywords, jComboBoxLoc.getSelectedItem().toString());
        } else {
            LuuDuLieu.dsPTCT = pmc.locPhieuTra(null, null, keywords, jComboBoxLoc.getSelectedItem().toString());
        }
        loadTable();
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tuNgay = sdf.format(jDateChooserTu.getDate());
        String denNgay = sdf.format(jDateChooserDen.getDate());
        LuuDuLieu.dsPTCT = pmc.locPhieuTra(tuNgay, denNgay, keywords,jComboBoxLoc.getSelectedItem().toString());
        loadTable();
    }//GEN-LAST:event_jButtonLocActionPerformed

    private void jTablePhieuTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePhieuTraMouseClicked
//        selectedRow = jTableMuonSach.getSelectedRow();
//        LuuDuLieu.currentPhieuMuonChiTiet = LuuDuLieu.dsPMCT.get(selectedRow);
    }//GEN-LAST:event_jTablePhieuTraMouseClicked

    private void jButtonTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaiLaiActionPerformed
        LuuDuLieu.dsPTCT = pmc.getPMCTDaTra();
        loadTable();
        jDateChooserDen.setDate(null);
        jDateChooserTu.setDate(null);
        jComboBoxLoc.setSelectedIndex(0);
        jTextKeyWord.setText("");
    }//GEN-LAST:event_jButtonTaiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoc;
    private javax.swing.JButton jButtonTaiLai;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JComboBox<String> jComboBoxLoc;
    private com.toedter.calendar.JDateChooser jDateChooserDen;
    private com.toedter.calendar.JDateChooser jDateChooserTu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTongPhieuTra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePhieuTra;
    private javax.swing.JTextField jTextKeyWord;
    // End of variables declaration//GEN-END:variables
}
