/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sach;

import QLTVController.SachController;
import QLTVController.TheLoaiController;
import QLTVModel.SachClass;
import QLTVModel.TheLoaiClass;
import Util.CustomTableSach;
import Util.IntegerValidate;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.util.Locale;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.text.NumberFormat;
import javax.swing.ButtonGroup;

/**
 *
 * @author WIN1064
 */
public class QuanLySach extends javax.swing.JPanel {

    SachController sc = new SachController();
    TheLoaiController tlc = new TheLoaiController();
    int selectedRow;
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    Vector<TheLoaiClass> dsTL;
    public static QuanLySach qlsach;
    String tongSach, tongSachMuon, tongSachBan;

    /**
     * Creates new form QuanLySach
     */
    public QuanLySach() {
        initComponents();
        ButtonGroup btn = new ButtonGroup();
        btn.add(jRadioMuon);
        btn.add(jRadioBan);
        jRadioMuon.setSelected(true);
        qlsach = this;
        LuuDuLieu.dsSach = sc.getSach();
        dsTL = new Vector<TheLoaiClass>(tlc.getTL());
        jComboBoxTL.setModel(new DefaultComboBoxModel(dsTL));
        jTableSach.getTableHeader().setDefaultRenderer(new StyleHeaderTable());
        renderer.setHorizontalAlignment(JLabel.CENTER);
        CustomTableSach ct = new CustomTableSach();
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableSach.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTableSach.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableSach.getColumnModel().getColumn(1).setPreferredWidth(120);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextGia = new javax.swing.JTextField();
        jTextSoLuong = new javax.swing.JTextField();
        jTextNXB = new javax.swing.JTextField();
        jTextTaiBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextTenSach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextMaSach = new javax.swing.JTextField();
        jComboBoxTL = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioMuon = new javax.swing.JRadioButton();
        jRadioBan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonXoa = new javax.swing.JButton();
        jButtonThemSach = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jTextKeyWords = new javax.swing.JTextField();
        jLabelTongSach = new javax.swing.JLabel();
        jLabelTongSachMuon = new javax.swing.JLabel();
        jLabelTongSachBan = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Thể loại");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên sách");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nhà xuất bản");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Giá");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tái bản");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã sách");

        jTextMaSach.setEditable(false);

        jComboBoxTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mục đích");

        jRadioMuon.setText("Sách mượn");

        jRadioBan.setText("Sách bán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(47, 47, 47)
                            .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioMuon)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioBan))
                                .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioMuon)
                    .addComponent(jRadioBan))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextGia)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTableSach.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableSach.setRowHeight(25);
        jTableSach.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableSach.setShowVerticalLines(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jTableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSach);

        jButtonXoa.setBackground(new java.awt.Color(0, 204, 204));
        jButtonXoa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deletebook.png"))); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.setBorder(null);
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonThemSach.setBackground(new java.awt.Color(0, 204, 204));
        jButtonThemSach.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addbook.png"))); // NOI18N
        jButtonThemSach.setText("Thêm sách");
        jButtonThemSach.setBorder(null);
        jButtonThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemSachActionPerformed(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.setBorder(null);
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonSua.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSua.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifybook.png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setBorder(null);
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jTextKeyWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKeyWordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextKeyWords))
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelTongSach.setText("Tổng số đầu sách :");

        jLabelTongSachMuon.setText("Tổng số đầu sách để mượn :");

        jLabelTongSachBan.setText("Tổng số đầu sách để bán :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTongSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45))
                            .addComponent(jLabelTongSachMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTongSachBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addGap(487, 487, 487)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongSachMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongSachBan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadTable() {
        jTableSach.setModel(new CustomTableSach());
        jTableSach.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTableSach.getColumnModel().getColumn(0).setCellRenderer(renderer);
        jTableSach.getColumnModel().getColumn(1).setPreferredWidth(120);
        CustomTableSach ct = new CustomTableSach();
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableSach.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        
        thongKe();
    }

    public void xoaTrang() {
        jTextMaSach.setText("");
        jTextTenSach.setText("");
        jTextGia.setText("");
        jTextNXB.setText("");
        jTextSoLuong.setText("");
        jTextTaiBan.setText("");
        jComboBoxTL.setSelectedIndex(0);
    }

    public void thongKe() {
        tongSach = Integer.toString(LuuDuLieu.dsSach.size());
        tongSachMuon = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 1).count());
        tongSachBan = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 0).count());
        jLabelTongSach.setText("Tổng sách : " + tongSach);
        jLabelTongSachMuon.setText("Tổng sách mượn : " + tongSachMuon);
        jLabelTongSachBan.setText("Tổng sách bán : " + tongSachBan);
    }
    private void jTableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSachMouseClicked
        selectedRow = jTableSach.getSelectedRow();
        SachClass s = LuuDuLieu.dsSach.get(selectedRow);
        jTextMaSach.setText(s.getMaSach() + "");
        jTextTenSach.setText(s.getTenSach() + "");
        if (s.getMucDich() == 1) {
            jRadioMuon.setSelected(true);
        } else {
            jRadioBan.setSelected(true);
        }
        jTextNXB.setText(s.getNhaXuatBan() + "");
        TheLoaiClass t = new TheLoaiClass();
        try {
            t.setMaTheLoai(s.getMaTheLoai());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        jComboBoxTL.setSelectedItem(dsTL.get(dsTL.indexOf(t)));
        jTextTaiBan.setText(Integer.toString(s.getTaiBan()) + "");
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        jTextGia.setText(vn.format(s.getGia()));
        jTextSoLuong.setText(Integer.toString(s.getSoLuong()) + "");
    }//GEN-LAST:event_jTableSachMouseClicked

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        selectedRow = jTableSach.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Phải chọn dòng muốn xóa");
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa sách này?", "Xác nhận",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == 0) {
                SachClass s = LuuDuLieu.dsSach.get(selectedRow);
                sc.xoaSach(s);
                loadTable();
                selectedRow = -1;
                xoaTrang();
                tongSach = Integer.toString(LuuDuLieu.dsSach.size());
                tongSachMuon = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 1).count());
                tongSachBan = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 0).count());
                thongKe();
            }
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemSachActionPerformed
        setVisible(false);
        ThemSach ts = new ThemSach();
        ts.setVisible(true);
    }//GEN-LAST:event_jButtonThemSachActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        LuuDuLieu.dsSach = sc.timKiem(jTextKeyWords.getText());
        loadTable();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed

        selectedRow = jTableSach.getSelectedRow();
        TheLoaiClass tlcl = (TheLoaiClass) jComboBoxTL.getSelectedItem();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Phải chọn sách cần sửa");
        } else {
            int op = JOptionPane.showConfirmDialog(null,
                    "Bạn xác nhận sửa sách này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                SachClass s = new SachClass();
                try {
                    s.setMaSach(jTextMaSach.getText());
                    s.setTenSach(jTextTenSach.getText());

                    if (!IntegerValidate.isInteger(jTextTaiBan.getText())) {
                        throw new Exception("tái bản sai định dạng");
                    } else {
                        s.setTaiBan(Integer.parseInt(jTextTaiBan.getText()));
                    }
                    s.setNhaXuatBan(jTextNXB.getText());
                    s.setMaTheLoai(tlcl.getMaTheLoai());
                    String gia = jTextGia.getText().replaceAll("\\.", "");
                    if (!IntegerValidate.isInteger(gia)) {
                        throw new Exception("giá sai định dạng");
                    } else {
                        s.setGia(Integer.parseInt(gia));
                    }
                    if (!IntegerValidate.isInteger(jTextSoLuong.getText())) {
                        throw new Exception("tái bản sai định dạng");
                    } else {
                        s.setSoLuong(Integer.parseInt(jTextSoLuong.getText()));
                    }
                    if (jRadioMuon.isSelected()) {
                        s.setMucDich(1);
                    } else {
                        s.setMucDich(0);
                    }
                    sc/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sach;

import QLTVController.SachController;
import QLTVController.TheLoaiController;
import QLTVModel.SachClass;
import QLTVModel.TheLoaiClass;
import Util.CustomTableSach;
import Util.IntegerValidate;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.util.Locale;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.text.NumberFormat;
import javax.swing.ButtonGroup;

/**
 *
 * @author WIN1064
 */
public class QuanLySach extends javax.swing.JPanel {

    SachController sc = new SachController();
    TheLoaiController tlc = new TheLoaiController();
    int selectedRow;
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    Vector<TheLoaiClass> dsTL;
    public static QuanLySach qlsach;
    String tongSach, tongSachMuon, tongSachBan;

    /**
     * Creates new form QuanLySach
     */
    public QuanLySach() {
        initComponents();
        ButtonGroup btn = new ButtonGroup();
        btn.add(jRadioMuon);
        btn.add(jRadioBan);
        jRadioMuon.setSelected(true);
        qlsach = this;
        LuuDuLieu.dsSach = sc.getSach();
        dsTL = new Vector<TheLoaiClass>(tlc.getTL());
        jComboBoxTL.setModel(new DefaultComboBoxModel(dsTL));
        jTableSach.getTableHeader().setDefaultRenderer(new StyleHeaderTable());
        renderer.setHorizontalAlignment(JLabel.CENTER);
        CustomTableSach ct = new CustomTableSach();
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableSach.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTableSach.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableSach.getColumnModel().getColumn(1).setPreferredWidth(120);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextGia = new javax.swing.JTextField();
        jTextSoLuong = new javax.swing.JTextField();
        jTextNXB = new javax.swing.JTextField();
        jTextTaiBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextTenSach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextMaSach = new javax.swing.JTextField();
        jComboBoxTL = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioMuon = new javax.swing.JRadioButton();
        jRadioBan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonXoa = new javax.swing.JButton();
        jButtonThemSach = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jTextKeyWords = new javax.swing.JTextField();
        jLabelTongSach = new javax.swing.JLabel();
        jLabelTongSachMuon = new javax.swing.JLabel();
        jLabelTongSachBan = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Thể loại");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên sách");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nhà xuất bản");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Giá");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tái bản");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã sách");

        jTextMaSach.setEditable(false);

        jComboBoxTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mục đích");

        jRadioMuon.setText("Sách mượn");

        jRadioBan.setText("Sách bán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(47, 47, 47)
                            .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jRadioMuon)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadioBan))
                                .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioMuon)
                    .addComponent(jRadioBan))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextGia)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTableSach.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableSach.setRowHeight(25);
        jTableSach.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableSach.setShowVerticalLines(false);
        jTableSach.getTableHeader().setReorderingAllowed(false);
        jTableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSach);

        jButtonXoa.setBackground(new java.awt.Color(0, 204, 204));
        jButtonXoa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deletebook.png"))); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.setBorder(null);
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonThemSach.setBackground(new java.awt.Color(0, 204, 204));
        jButtonThemSach.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addbook.png"))); // NOI18N
        jButtonThemSach.setText("Thêm sách");
        jButtonThemSach.setBorder(null);
        jButtonThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemSachActionPerformed(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.setBorder(null);
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonSua.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSua.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modifybook.png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setBorder(null);
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jTextKeyWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKeyWordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextKeyWords))
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelTongSach.setText("Tổng số đầu sách :");

        jLabelTongSachMuon.setText("Tổng số đầu sách để mượn :");

        jLabelTongSachBan.setText("Tổng số đầu sách để bán :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTongSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45))
                            .addComponent(jLabelTongSachMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTongSachBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addGap(487, 487, 487)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongSachMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTongSachBan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadTable() {
        jTableSach.setModel(new CustomTableSach());
        jTableSach.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTableSach.getColumnModel().getColumn(0).setCellRenderer(renderer);
        jTableSach.getColumnModel().getColumn(1).setPreferredWidth(120);
        CustomTableSach ct = new CustomTableSach();
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableSach.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        
        thongKe();
    }

    public void xoaTrang() {
        jTextMaSach.setText("");
        jTextTenSach.setText("");
        jTextGia.setText("");
        jTextNXB.setText("");
        jTextSoLuong.setText("");
        jTextTaiBan.setText("");
        jComboBoxTL.setSelectedIndex(0);
    }

    public void thongKe() {
        tongSach = Integer.toString(LuuDuLieu.dsSach.size());
        tongSachMuon = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 1).count());
        tongSachBan = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 0).count());
        jLabelTongSach.setText("Tổng sách : " + tongSach);
        jLabelTongSachMuon.setText("Tổng sách mượn : " + tongSachMuon);
        jLabelTongSachBan.setText("Tổng sách bán : " + tongSachBan);
    }
    private void jTableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSachMouseClicked
        selectedRow = jTableSach.getSelectedRow();
        SachClass s = LuuDuLieu.dsSach.get(selectedRow);
        jTextMaSach.setText(s.getMaSach() + "");
        jTextTenSach.setText(s.getTenSach() + "");
        if (s.getMucDich() == 1) {
            jRadioMuon.setSelected(true);
        } else {
            jRadioBan.setSelected(true);
        }
        jTextNXB.setText(s.getNhaXuatBan() + "");
        TheLoaiClass t = new TheLoaiClass();
        try {
            t.setMaTheLoai(s.getMaTheLoai());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        jComboBoxTL.setSelectedItem(dsTL.get(dsTL.indexOf(t)));
        jTextTaiBan.setText(Integer.toString(s.getTaiBan()) + "");
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        jTextGia.setText(vn.format(s.getGia()));
        jTextSoLuong.setText(Integer.toString(s.getSoLuong()) + "");
    }//GEN-LAST:event_jTableSachMouseClicked

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        selectedRow = jTableSach.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Phải chọn dòng muốn xóa");
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa sách này?", "Xác nhận",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == 0) {
                SachClass s = LuuDuLieu.dsSach.get(selectedRow);
                sc.xoaSach(s);
                loadTable();
                selectedRow = -1;
                xoaTrang();
                tongSach = Integer.toString(LuuDuLieu.dsSach.size());
                tongSachMuon = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 1).count());
                tongSachBan = Integer.toString((int) LuuDuLieu.dsSach.stream().filter(i -> i.getMucDich() == 0).count());
                thongKe();
            }
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemSachActionPerformed
        setVisible(false);
        ThemSach ts = new ThemSach();
        ts.setVisible(true);
    }//GEN-LAST:event_jButtonThemSachActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        LuuDuLieu.dsSach = sc.timKiem(jTextKeyWords.getText());
        loadTable();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed

        selectedRow = jTableSach.getSelectedRow();
        TheLoaiClass tlcl = (TheLoaiClass) jComboBoxTL.getSelectedItem();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Phải chọn sách cần sửa");
        } else {
            int op = JOptionPane.showConfirmDialog(null,
                    "Bạn xác nhận sửa sách này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                SachClass s = new SachClass();
                try {
                    s.setMaSach(jTextMaSach.getText());
                    s.setTenSach(jTextTenSach.getText());

                    if (!IntegerValidate.isInteger(jTextTaiBan.getText())) {
                        throw new Exception("tái bản sai định dạng");
                    } else {
                        s.setTaiBan(Integer.parseInt(jTextTaiBan.getText()));
                    }
                    s.setNhaXuatBan(jTextNXB.getText());
                    s.setMaTheLoai(tlcl.getMaTheLoai());
                    String gia = jTextGia.getText().replaceAll("\\.", "");
                    if (!IntegerValidate.isInteger(gia)) {
                        throw new Exception("giá sai định dạng");
                    } else {
                        s.setGia(Integer.parseInt(gia));
                    }
                    if (!IntegerValidate.isInteger(jTextSoLuong.getText())) {
                        throw new Exception("tái bản sai định dạng");
                    } else {
                        s.setSoLuong(Integer.parseInt(jTextSoLuong.getText()));
                    }
                    if (jRadioMuon.isSelected()) {
                        s.setMucDich(1);
                    } else {
                        s.setMucDich(0);
                    }
                    sc.suaSach(s);
                    selectedRow = -1;
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Thông tin " + ex.getMessage());
                }

                loadTable();
            }
        }


    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jTextKeyWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKeyWordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKeyWordsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThemSach;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTongSach;
    private javax.swing.JLabel jLabelTongSachBan;
    private javax.swing.JLabel jLabelTongSachMuon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBan;
    private javax.swing.JRadioButton jRadioMuon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextField jTextGia;
    private javax.swing.JTextField jTextKeyWords;
    private javax.swing.JTextField jTextMaSach;
    private javax.swing.JTextField jTextNXB;
    private javax.swing.JTextField jTextSoLuong;
    private javax.swing.JTextField jTextTaiBan;
    private javax.swing.JTextField jTextTenSach;
    // End of variables declaration//GEN-END:variables
}
