/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sach;

import Connect.ConnectToSql;
import QLTVController.SachController;
import QLTVController.SinhVienController;
import QLTVController.TheLoaiController;
import QLTVModel.SachClass;
import QLTVModel.SinhVienClass;
import QLTVModel.TheLoaiClass;
import Util.DoubleValidate;
import Util.IntegerValidate;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN1064
 */
public class ThemSach extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Vector<TheLoaiClass> dsTL;
    TheLoaiController tlc = new TheLoaiController();

    /**
     * Creates new form ThemSach
     */
    public ThemSach() {
        super("ThemSach");
        initComponents();
        ButtonGroup btn = new ButtonGroup();
        btn.add(jRadioMua);
        btn.add(jRadioMuon);
        jRadioMuon.setSelected(true);
        dsTL = new Vector<TheLoaiClass>(tlc.getTL());
        jComboBoxTL.setModel(new DefaultComboBoxModel(dsTL));
    }

    public void xoaTrang() {
        jTextTenSach.setText("");
        jTextNXB.setText("");
        jComboBoxTL.setSelectedIndex(0);
        jTextTaiBan.setText("");
        jTextGia.setText("");
        jTextSoLuong.setText("");
        jRadioMuon.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBtnQuayLai = new javax.swing.JButton();
        jTextGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNXB = new javax.swing.JTextField();
        jBtnThemSach = new javax.swing.JButton();
        jTextTenSach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextTaiBan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextSoLuong = new javax.swing.JTextField();
        jComboBoxTL = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioMuon = new javax.swing.JRadioButton();
        jRadioMua = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Thêm sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên sách");

        jBtnQuayLai.setBackground(new java.awt.Color(0, 204, 204));
        jBtnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jBtnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jBtnQuayLai.setText("Quay lại");
        jBtnQuayLai.setBorder(null);
        jBtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuayLaiActionPerformed(evt);
            }
        });

        jTextGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGiaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Giá");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thể loại");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nhà xuất bản");

        jBtnThemSach.setBackground(new java.awt.Color(0, 204, 204));
        jBtnThemSach.setForeground(new java.awt.Color(255, 255, 255));
        jBtnThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addbook.png"))); // NOI18N
        jBtnThemSach.setText("Thêm sách");
        jBtnThemSach.setBorder(null);
        jBtnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemSachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tái bản");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Số lượng");

        jComboBoxTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mục đích");

        jRadioMuon.setText("Sách mượn");

        jRadioMua.setText("Sách mua");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jRadioMuon)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioMua))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jBtnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioMuon)
                    .addComponent(jRadioMua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(468, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuayLaiActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnQuayLaiActionPerformed

    private void jBtnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemSachActionPerformed

        SachController sc = new SachController();
        LuuDuLieu.currentSach = new SachClass();
        TheLoaiClass tlcl = (TheLoaiClass) jComboBoxTL.getSelectedItem();
        try {
            LuuDuLieu.currentSach.setTenSach(jTextTenSach.getText());

            if (!IntegerValidate.isInteger(jTextTaiBan.getText())) {
                throw new Exception("tái bản sai định dạng");
            } else {
                LuuDuLieu.currentSach.setTaiBan(Integer.parseInt(jTextTaiBan.getText()));
            }
            LuuDuLieu.currentSach.setNhaXuatBan(jTextNXB.getText());
            LuuDuLieu.currentSach.setMaTheLoai(tlcl.getMaTheLoai());
            if (!IntegerValidate.isInteger(jTextGia.getText())) {
                throw new Exception("giá sai định dạng");
            } else {
                LuuDuLieu.currentSach.setGia(Integer.parseInt(jTextGia.getText()));
            }
            if (!IntegerValidate.isInteger(jTextSoLuong.getText())) {
                throw new Exception("tái bản sai định dạng");
            } else {
                LuuDuLieu.currentSach.setSoLuong(Integer.parseInt(jTextSoLuong.getText()));
            }
            if (jRadioMuon.isSelected()) {
                LuuDuLieu.currentSach.setMucDich(1);
            } else {
                LuuDuLieu.currentSach.setMucDich(0);
            }
            int input = JOptionPane.showConfirmDialog(null, "Xác nhận thêm sách?", "Thêm sách", JOptionPane.YES_NO_OPTION);
            if (input == 0) {
                sc.themSach(LuuDuLieu.currentSach);
                QuanLySach.qlsach.loadTable();
                xoaTrang();

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thông tin " + ex.getMessage());
        }

//        String sql = "EXEC InsertSach @tenSach = ?, @taiBan = ?, @nxb = ?,@theLoai = ? , @soTrang = ?, @gia = ?, @soLuong = ?";
//        try{
//            pst = conn.prepareStatement(sql);
//            pst.setString(1, jTextTenSach.getText());
//            pst.setString(2, jTextTaiBan.getText());
//            pst.setString(3, jTextNXB.getText());
//            pst.setString(4, jTextTheLoai.getText());
//            pst.setString(5, jTextSoTrang.getText());
//            pst.setString(6, jTextSoTrang.getText());
//            pst.setString(7, jTextSoLuong.getText());
//            pst.execute();
//            JOptionPane.showMessageDialog(null, "Thêm sách thành công");
//        }catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }

    }//GEN-LAST:event_jBtnThemSachActionPerformed

    private void jTextGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSach().setVisible(true);
            /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sach;

import Connect.ConnectToSql;
import QLTVController.SachController;
import QLTVController.SinhVienController;
import QLTVController.TheLoaiController;
import QLTVModel.SachClass;
import QLTVModel.SinhVienClass;
import QLTVModel.TheLoaiClass;
import Util.DoubleValidate;
import Util.IntegerValidate;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN1064
 */
public class ThemSach extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Vector<TheLoaiClass> dsTL;
    TheLoaiController tlc = new TheLoaiController();

    /**
     * Creates new form ThemSach
     */
    public ThemSach() {
        super("ThemSach");
        initComponents();
        ButtonGroup btn = new ButtonGroup();
        btn.add(jRadioMua);
        btn.add(jRadioMuon);
        jRadioMuon.setSelected(true);
        dsTL = new Vector<TheLoaiClass>(tlc.getTL());
        jComboBoxTL.setModel(new DefaultComboBoxModel(dsTL));
    }

    public void xoaTrang() {
        jTextTenSach.setText("");
        jTextNXB.setText("");
        jComboBoxTL.setSelectedIndex(0);
        jTextTaiBan.setText("");
        jTextGia.setText("");
        jTextSoLuong.setText("");
        jRadioMuon.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBtnQuayLai = new javax.swing.JButton();
        jTextGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNXB = new javax.swing.JTextField();
        jBtnThemSach = new javax.swing.JButton();
        jTextTenSach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextTaiBan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextSoLuong = new javax.swing.JTextField();
        jComboBoxTL = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jRadioMuon = new javax.swing.JRadioButton();
        jRadioMua = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Thêm sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên sách");

        jBtnQuayLai.setBackground(new java.awt.Color(0, 204, 204));
        jBtnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        jBtnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jBtnQuayLai.setText("Quay lại");
        jBtnQuayLai.setBorder(null);
        jBtnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuayLaiActionPerformed(evt);
            }
        });

        jTextGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGiaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Giá");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thể loại");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nhà xuất bản");

        jBtnThemSach.setBackground(new java.awt.Color(0, 204, 204));
        jBtnThemSach.setForeground(new java.awt.Color(255, 255, 255));
        jBtnThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addbook.png"))); // NOI18N
        jBtnThemSach.setText("Thêm sách");
        jBtnThemSach.setBorder(null);
        jBtnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemSachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tái bản");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Số lượng");

        jComboBoxTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mục đích");

        jRadioMuon.setText("Sách mượn");

        jRadioMua.setText("Sách mua");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jRadioMuon)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioMua))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jBtnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioMuon)
                    .addComponent(jRadioMua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(468, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuayLaiActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnQuayLaiActionPerformed

    private void jBtnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemSachActionPerformed

        SachController sc = new SachController();
        LuuDuLieu.currentSach = new SachClass();
        TheLoaiClass tlcl = (TheLoaiClass) jComboBoxTL.getSelectedItem();
        try {
            LuuDuLieu.currentSach.setTenSach(jTextTenSach.getText());

            if (!IntegerValidate.isInteger(jTextTaiBan.getText())) {
                throw new Exception("tái bản sai định dạng");
            } else {
                LuuDuLieu.currentSach.setTaiBan(Integer.parseInt(jTextTaiBan.getText()));
            }
            LuuDuLieu.currentSach.setNhaXuatBan(jTextNXB.getText());
            LuuDuLieu.currentSach.setMaTheLoai(tlcl.getMaTheLoai());
            if (!IntegerValidate.isInteger(jTextGia.getText())) {
                throw new Exception("giá sai định dạng");
            } else {
                LuuDuLieu.currentSach.setGia(Integer.parseInt(jTextGia.getText()));
            }
            if (!IntegerValidate.isInteger(jTextSoLuong.getText())) {
                throw new Exception("tái bản sai định dạng");
            } else {
                LuuDuLieu.currentSach.setSoLuong(Integer.parseInt(jTextSoLuong.getText()));
            }
            if (jRadioMuon.isSelected()) {
                LuuDuLieu.currentSach.setMucDich(1);
            } else {
                LuuDuLieu.currentSach.setMucDich(0);
            }
            int input = JOptionPane.showConfirmDialog(null, "Xác nhận thêm sách?", "Thêm sách", JOptionPane.YES_NO_OPTION);
            if (input == 0) {
                sc.themSach(LuuDuLieu.currentSach);
                QuanLySach.qlsach.loadTable();
                xoaTrang();

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thông tin " + ex.getMessage());
        }

//        String sql = "EXEC InsertSach @tenSach = ?, @taiBan = ?, @nxb = ?,@theLoai = ? , @soTrang = ?, @gia = ?, @soLuong = ?";
//        try{
//            pst = conn.prepareStatement(sql);
//            pst.setString(1, jTextTenSach.getText());
//            pst.setString(2, jTextTaiBan.getText());
//            pst.setString(3, jTextNXB.getText());
//            pst.setString(4, jTextTheLoai.getText());
//            pst.setString(5, jTextSoTrang.getText());
//            pst.setString(6, jTextSoTrang.getText());
//            pst.setString(7, jTextSoLuong.getText());
//            pst.execute();
//            JOptionPane.showMessageDialog(null, "Thêm sách thành công");
//        }catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }

    }//GEN-LAST:event_jBtnThemSachActionPerformed

    private void jTextGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnQuayLai;
    private javax.swing.JButton jBtnThemSach;
    private javax.swing.JComboBox<String> jComboBoxTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioMua;
    private javax.swing.JRadioButton jRadioMuon;
    private javax.swing.JTextField jTextGia;
    private javax.swing.JTextField jTextNXB;
    private javax.swing.JTextField jTextSoLuong;
    private javax.swing.JTextField jTextTaiBan;
    private javax.swing.JTextField jTextTenSach;
    // End of variables declaration//GEN-END:variables
}
